# Generated by Django 4.1.1 on 2022-10-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeday',
            name='theClass',
            field=models.ManyToManyField(null=True, through='attendance.Attendance', to='attendance.class'),
        ),
    ]
