# Generated by Django 4.1.1 on 2022-09-30 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.course'),
        ),
        migrations.AddField(
            model_name='class',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.lecturer'),
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.ManyToManyField(to='attendance.semester'),
        ),
        migrations.AddField(
            model_name='class',
            name='student',
            field=models.ManyToManyField(blank=True, to='attendance.student'),
        ),
    ]
