# Generated by Django 4.1.1 on 2022-09-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_class_course_class_lecturer_class_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, to='attendance.student'),
        ),
    ]
