# Generated by Django 4.1.1 on 2022-09-30 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_class_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='semester',
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.semester'),
        ),
    ]
