# Generated by Django 4.1.1 on 2022-10-01 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_class_semester_class_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.course'),
        ),
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.semester'),
        ),
        migrations.AlterField(
            model_name='class',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, to='attendance.student', verbose_name='student'),
        ),
    ]
